import { useState } from 'react'
import { createRealOrFakeRound } from './gameData.js'
import SocialSharePanel from './SocialSharePanel.jsx'
import PageMeta from '../PageMeta.jsx'

const getShareText = (score) => `I scored ${score}/5 on Daily Nugget: Real or Fake.`
const getShareUrl = () => `${window.location.origin}/games/real-or-fake`

export default function RealOrFakeMode() {
  const [questions, setQuestions] = useState(createRealOrFakeRound)
  const [currentQuestionIndex, setCurrentQuestionIndex] = useState(0)
  const [score, setScore] = useState(0)
  const [selectedAnswer, setSelectedAnswer] = useState('')
  const [gameComplete, setGameComplete] = useState(false)
  const [shareStatus, setShareStatus] = useState('')

  const currentQuestion = questions[currentQuestionIndex]
  const isLastQuestion = currentQuestionIndex === questions.length - 1
  const shareMessage = getShareText(score)
  const shareUrl = getShareUrl()

  const handleGuess = (guess) => {
    if (selectedAnswer) return

    setSelectedAnswer(guess)

    if (guess === currentQuestion.answer) {
      setScore((currentScore) => currentScore + 1)
    }
  }

  const nextQuestion = () => {
    if (isLastQuestion) {
      setGameComplete(true)
      return
    }

    setCurrentQuestionIndex((index) => index + 1)
    setSelectedAnswer('')
  }

  const playAgain = () => {
    setQuestions(createRealOrFakeRound())
    setCurrentQuestionIndex(0)
    setScore(0)
    setSelectedAnswer('')
    setGameComplete(false)
    setShareStatus('')
  }

  const shareResult = async () => {
    if (navigator.share) {
      try {
        await navigator.share({
          title: 'Daily Nugget: Real or Fake',
          text: shareMessage,
          url: shareUrl,
        })
        setShareStatus('Share sheet opened.')
        return
      } catch (error) {
        if (error.name === 'AbortError') return
      }
    }

    copyShareText()
  }

  const copyShareText = async (textToCopy = `${shareMessage} ${shareUrl}`) => {
    try {
      await navigator.clipboard.writeText(textToCopy)
      setShareStatus('Copied.')
    } catch {
      setShareStatus(textToCopy)
    }
  }

  if (gameComplete) {
    return (
      <main className="challenge-page">
        <section className="challenge-shell challenge-results text-center">
          <p className="challenge-kicker">Real or Fake</p>
          <h1>You scored {score}/5</h1>
          <p className="challenge-message">You spotted {score} quote source{score === 1 ? '' : 's'} correctly.</p>
          <div className="challenge-actions">
            <button className="btn btn-blackburn-gold" type="button" onClick={shareResult}>
              Share Result
            </button>
            <button className="btn btn-outline-light" type="button" onClick={playAgain}>
              Play Again
            </button>
          </div>
          <SocialSharePanel
            message={shareMessage}
            url={shareUrl}
            emailSubject="Daily Nugget: Real or Fake"
            onCopy={copyShareText}
          />
          {shareStatus && <p className="challenge-share-status">{shareStatus}</p>}
        </section>
      </main>
    )
  }

  return (
    <main className="challenge-page">
      <PageMeta
        title="Real or Fake: AI vs Human"
        description="Play Daily Nugget Real or Fake and guess whether motivational quotes were written by a real person or generated by AI."
        path="/games/real-or-fake"
      />
      <section className="challenge-shell game-mode-shell">
        <div className="challenge-hero">
          <div>
            <p className="challenge-kicker">Real or Fake: AI vs Human</p>
            <h1>Who wrote the nugget?</h1>
            <p>Read the quote and guess whether it came from a real person or was generated by AI.</p>
          </div>
          <div className="game-score-stack">
            <span>Question {currentQuestionIndex + 1} of {questions.length}</span>
            <span>Score: {score}</span>
          </div>
        </div>

        <article className="challenge-card real-or-fake-card">
          <blockquote>{currentQuestion.quote}</blockquote>

          <div className="real-fake-options">
            <button
              className={`challenge-option ${selectedAnswer === 'real' ? 'is-selected' : ''}`}
              type="button"
              onClick={() => handleGuess('real')}
              disabled={Boolean(selectedAnswer)}
            >
              Real Quote
            </button>
            <button
              className={`challenge-option ${selectedAnswer === 'ai' ? 'is-selected' : ''}`}
              type="button"
              onClick={() => handleGuess('ai')}
              disabled={Boolean(selectedAnswer)}
            >
              AI Quote
            </button>
          </div>

          {selectedAnswer && (
            <div className="challenge-feedback">
              {selectedAnswer === currentQuestion.answer ? 'Correct.' : 'Incorrect.'} Source: {currentQuestion.author}
            </div>
          )}

          {selectedAnswer && (
            <button className="btn btn-blackburn-gold challenge-next" type="button" onClick={nextQuestion}>
              {isLastQuestion ? 'See Results' : 'Next'}
            </button>
          )}
        </article>
      </section>
    </main>
  )
}
